### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by frmdstryr** [edefazio/varcode#2]
Hi,

This is an interesting project. Do you have any benchmarks on this? How fast is it compared to using reflection for calling methods?

Thanks!

**Comment by edefazio** [comment]
Thanks for your interest...

At the moment I decided to do refactor this to (2) projects... The code itself if fine, but it seemed there were (2) projects each trying to get out:

- the template engine (self contained with no dependencies)
- AdHoc modelling Java code ( dependencies to JavaAST and dealing with ClassLoaders, etc.)

I want to be able to reuse the template engine to model and build all different types of code at runtime (C++, C, Java) and files (Maven build files, docker files, etc.). So it seemed logical that I break them apart.

So (FYI) I'm kinda in the midst of porting things... But I have used this code/done some back of the envelope calculations just to see how "fast" things are.

Really you have to keep in mind you only model/compile/load the Class once (this is the largest cost), after that you are pretty much just paying for a reflection call 

So, given those terms, I created a simple test bench (I should really use JMH or something, but this is just a back of the envelope calculation)

```
import exacts.java._class;
import exacts.java.adhoc.AdHocClassLoader;
import exacts.java.adhoc.Project;

public class Perf{
 
    public static void main( String[] args ){
        int count = 1000;
        long start = System.currentTimeMillis();
        Project p = new Project();
        
        for( int i = 0;i < count;i++ ){
            p.add( _class.of( "A" + i )
                .addMethod("public static double getId()", "return Math.random();") );            
        }        
        long finishedBuildingModels = System.currentTimeMillis();
        AdHocClassLoader adHoc = p.compile();
        long finishedCompiling = System.currentTimeMillis();        
        System.out.println( "Building Code took "+( finishedBuildingModels - start )+"ms ");
        System.out.println( "Compiling Code took "+( finishedCompiling - finishedBuildingModels)+"ms ");
        System.out.println( "AdHoc Build/Compile code time "+( finishedCompiling - start )+"ms ");
        
        //call each adHoc class's getIdMethod
        double total = 0;
        long startedCallingAdHocMethods = System.currentTimeMillis();
        Class a1 = adHoc.classByName( "A1" );
        try{
            for(int i=0;i<count;i++) {
            //total += (double)Java.call( adHoc.classByName( "A"+i ), "getId" );
            //total += (double)Java.call( adHoc.classByName( "A1" ), "getId" );
                total += (double)a1.getMethod( "getId").invoke( null );
            }
        }catch(Exception e) {
        }
        
        double otherTotal = 0.0;
        long finishedCallingReflectiveAdHocMethods = System.currentTimeMillis();
        try{
            for(int i=0;i<count;i++) {
                otherTotal += (double)APrioriClass.class.getMethod( "getId" ).invoke( null );
            }
        }catch(Exception e) {
        }
        long finishedCallingReflectiveAPrioriMethod = System.currentTimeMillis();
        
        double lastTotal = 0.0d;
        for(int i=0;i<count;i++) {
            lastTotal += APrioriClass.getId();
        }
        long directCallStaticMethod = System.currentTimeMillis();        
        System.out.println( "AdHoc Reflective Static method took "+ (finishedCallingReflectiveAdHocMethods - startedCallingAdHocMethods)+"ms:  got "+ total );
        System.out.println( "AdPriori Reflective Static method took "+ (finishedCallingReflectiveAPrioriMethod - finishedCallingReflectiveAdHocMethods)+"ms: got "+ otherTotal );
        System.out.println( "AdPriori Direct method took "+ (directCallStaticMethod - finishedCallingReflectiveAPrioriMethod)+"ms: got "+ lastTotal );
        
    }
    
    public static class APrioriClass{
        public static double getId() {
            return Math.random();
        }        
    }    
}
```
Running it cold:

Building Code took 421ms (1000 adhoc classes)
Compiling Code took 1745ms (1000 adhoc classes)
AdHoc Build Compile Code time: 2166ms (1000 adhoc classes)

**AdHoc Reflective Static method took 5ms:  got 486.29964491351274 (1000 calls)
AdPriori Reflective Static method took 2ms: got 507.0552343451649 (1000 calls)
AdPriori Direct method took 1ms: got 495.71825919975527 (1000 calls) **

YMMV depending on machine (this is an anemic 2 year old $300 desktop...)

NOTE: I tried making this as unbiased as possible but keep in mind there are plenty
of other tricks (i.e. the JIT) that make this test biased... just trying to give you ballpark numbers

**Comment by frmdstryr** [comment]
Thank you
